### ISSUE TITLE
Provide support for new Azure Monitor Metrics Dataplane API

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#2284]
### Proposal

Provide support for new Azure Monitor Metrics Dataplane API (preview) which has higher limitations and allows for scraping resources in batch.

https://azure.microsoft.com/en-us/updates/public-preview-azure-monitor-metrics-dataplane-api-released/

This should be configurable so that end-users can choose this new API next to existing ARM API.

### Component

Scraper

**Comment by tomkerkhove** [comment]
@hkfgo Can you please also update https://changelog.promitor.io/?

**Comment by tomkerkhove** [comment]
@hkfgo Can you please see if local tests are working with OpenTelemetry? I tried shipping new version 3 times but all those tests time out for metrics not showing up

https://dev.azure.com/tomkerkhove/Promitor/_build/results?buildId=14883&view=results

**Comment by hkfgo** [comment]
> @hkfgo Can you please see if local tests are working with OpenTelemetry? I tried shipping new version 3 times but all those tests time out for metrics not showing up
> 
> https://dev.azure.com/tomkerkhove/Promitor/_build/results?buildId=14883&view=results

Sure, I can test it out in our cloud env. We have OTEL Collectors running there. In my experience it take on average more than 3 tries for the OpenTelemetry CI to pass :/ In the most recent PR I merged, I had to retry 5 times

**Comment by hkfgo** [comment]
I got some unfortunate news @tomkerkhove, the OTEL Collector sink might actually be broken. I observe one successful metric export then nothing afterwards. That's probably why some times the CI tests were able to pass.

Not sure which version broke OTEL or why no one's filed an issue yet

**Comment by hkfgo** [comment]
But in any case, I'm working hard to track down the issue..

**Comment by tomkerkhove** [comment]
Thanks! Do you know if it's related to the new API change or broken in general?

**Comment by hkfgo** [comment]
> Thanks! Do you know if it's related to the new API change or broken in general?

Unlikely since no there hasn't been a code change on the OTEL sink for a year. Code changes in the past year should have no effect there. I'm running through older versions to pin down the latest version with a working OTEL sink(and thus when it broke). 

You are sure the OTEL sink worked smoothly at some point right?

**Comment by hkfgo** [comment]
@tomkerkhove I tracked down the latest version with a working OTEL sink, which is 2.8.0. That also means 2.9.0: https://github.com/tomkerkhove/promitor/releases/tag/Scraper-v2.9.0 was where things broke, over 1.5 years ago. Among the list of changes I suspect these two commits broke it: https://github.com/tomkerkhove/promitor/pull/2239 and https://github.com/tomkerkhove/promitor/pull/2235. There was also an upgrade to .Net 7. I'll need a bit more time to pin down the offending change. 

Taking a step back.. Given this piece of information, I'd consider all the recent changes safe, since they aren't the ones breaking OTEL sink. I'd also consider the broken OTEL sink not a blocker for release these recent changes.

**Comment by tomkerkhove** [comment]
I am not sure if I agree with that given the tests up to v2.11.2 were passing : https://dev.azure.com/tomkerkhove/Promitor/_build/results?buildId=13845&view=results

**Comment by tomkerkhove** [comment]
> Taking a step back.. Given this piece of information, I'd consider all the recent changes safe, since they aren't the ones breaking OTEL sink. I'd also consider the broken OTEL sink not a blocker for release these recent changes.

Not really or we'd break other end-users which is not really what we should do.

**Comment by hkfgo** [comment]
<img width="1450" alt="Screenshot 2024-11-01 at 2 56 36 PM" src="https://github.com/user-attachments/assets/70a3a9b6-bf9a-41c4-91c4-1e50d89dd614">
The reason why previous CI were able to pass was because the first export is often successful, but not subsequent ones. The screenshot above should help illustrate the point. This failure mode is insidious IMO because it can "trick" the CI to pass, all the while the sink is broken. 

Version 2.8.0 was the latest one that gave a continuous stream of metrics.

**Comment by tomkerkhove** [comment]
Let's move this to a seperate issue, but we'll need to fix that because:
1. End-users should not be broken
2. No way tests will be passing

If we cannot resolve by EOW,then I'll skip OTEL tests just to get the version out and re-enable them again

**Comment by hkfgo** [comment]
Ack, I'll open a new issue
