### ISSUE TITLE
Metrics interval does not take scraping cron schedule into account

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#60]
Currently every time a metric is scraped it will get a list of all measure points with a fixed interval, currently 1 minute.

This means that the scraping schedule, which is a cron, is not taken into account and can give false positives when using metrics such as average.

**Comment by jdevalk2** [comment]
I have an observation, which I think is an issue, related to this one, but not sure if its its own issue.

Sorry for the long story in advance.
The short of it is: When retrieving metrics, then Promitor should respect the underlying metric data granularities, and the data granularity should (probably?) be configurable on the Generic Metric definition configuration.

Here goes :

First consider a timeline, Azure Monitor will log a datapoint at intervals.

Then on top of this there is the concept of Azure Monitor data granularity.  Which data granularities are supported is depending on the underlying resource. When getting the resource metric definition, it will list its supported data granularity.  Common ones are 30s, 1m, 15m, 30m, 1h, 6h, 12h, 1d

Azure monitor already does aggregation from "raw" datapoints into the above data granularities.
Lets say for example the data granularity is one minute. In that minute AM could have retrieved 2 "raw" datapoints from the resource, those will then be aggregated (sum, total, avg, min, max)

Raw: 10 bytes at T + 15 seconds
Raw: 25 bytes at T + 20 seconds

Then 1 minute data granularity interval for TOTAL aggregation could be 35 bytes.
If those points are the only points in 15 minutes then
15 minute data granularity for TOTAL aggregation is 35 bytes.
1 hour data granularity for TOTAL aggregation is 35 bytes.
etc.

Now we have a cron job which fires data collector process every X interval.
Data collector process purpose is to get the latest measured datapoint for the observed metric.

It works by every interval the past 5 days of data is grabbed, in metric "data granularity" intervals.
That data granularity currently is set to 5 minutes, hardcoded.  

There is a TODO in the code that mentions that should be synced with the CRON job interval, but I think this should be synced with the data granularity interval that is configured by the user.

First consideration why I think this wouldn't be ideal is you could have many metrics configured. Each with a different data granularity so in that case it would be hard to have 1 CRON job schedule that would match the data granularity of all underlying metric configured to be measured.

Second consideration like said I think the data granularity instead of being 5m hardcoded should be configurable by the end user in the metric configuration.
In the Azure Monitor query API interval dictates the data granularity series (aggregated by Azure Monitor internally) that is returned.

That way if you had this below, which I think is the desired behaviour.
If the scraper runs after T+7 minutes you would expect V7 for metric1 and V2 for metric2

```
Metric1 (every minute) 
V1 V2 V3 V4 V5 V6 V7 V8

Metric2 (every 5 minutes)
V1                V2

Scraper
                             ^
```

In the current version you would have
If the scraper runs after T+7 minutes again with 5 minute hardcoded granularity
You would get V5 for metric 1 and V2 for metric2 

```
Metric1 (every minute) 
V1 V2 V3 V4 V5 V6 V7 V8

Metric2 (every 5 minutes)
V1                V2

Scraper
                             ^
```

**Comment by tomkerkhove** [comment]
Thanks for the thorough report @jdevalk2!

I can see you concern where the aggregations are not aligned and configuring them might be better indeed. However, wouldn't it be a problem if you use granularity 1 min but only scrape every 5 min?

I don't think it is but just want to make sure we've thought this through.

**Comment by jdevalk2** [comment]
@tomkerkhove 

Azure Monitor lowest known resolution of 1 minute - depending on the total timeline you are looking at - can be pretty coarse already. 

It does pre-aggregation within that 1-minute: min, max, average etc.  So at best in Promitor we already get a collapsed summarized view of the resource that is being monitored.

The case you mention where the resource is queried on per-minute-data-granularity and Promitor query loop runs by CRON every 5 minutes could result in a loss of data fidelity. This depends if Promitor should or should not have aggregation functionality of its own.

One solution could be that Promitor loop has to be as-fast as the lowest datagranularity of all the resources you are running.  Example: monitor a resource with 1 minute and one with 5 minute intervals. This example means Promitor has to run every minute.

One other option is Promitor does additional data aggregation, and it also knows the last data point it queried (timestamp) for each resource.  In this example, if Promitor is configured to scrape a resource with 1 minute granularity and 5 minute granularity intervals, and Promitor runs every 5 minutes. Promitor "knows" that it needs to aggregate the last 5 data points of the 1 minute resource and pass through the 5 minute one.

However I think the least complex would be for Promitor just to pass-through and not make any interpretations on the data itself.  

If Promitor passes through the data at the lowest resolution, then any aggregation can be taken care of in Prometheus query language, as I think that is what it is good at.

For instance resource 1 - 1 minute intervals, resource 2 - 5 minute intervals.

      Avg R1:   Avg R2:
T+0  10     20
T+1  20     20
T+2  10     20
T+3  40     20
T+4  85     20
T+5  100   30
T+5  60     30

You get 5 average values for R1, 10, 20, 10, 40, 85 for every 1 value in T2: 20
Then in PromQL you can hopefully normalize those 5 values into 1 value when comparing T1, T2.

Coming back to the case where a 1-minute granularity resource is scraped every 5 minutes. Given the alternative that no data aggregation is done, that means data fidelity is lost.

But from the point of taking metrics from a resource. All we do is look at the resource and observe the state that its in at that moment. If we missed the states before that it does not necessarily mean it is wrong, it just means when we have valleys and peaks our valleys and peaks would be chunkier with not as high a resolution.

**Comment by tomkerkhove** [comment]
For what it's worth, Promitor does **not** do any aggregation at the moment, it just scrapes on a fixed schedule but this is misleading indeed.

As the issue is bigger than aligning CRON for Promitor scraping & metrics aggregation I suggest to pick this up in #198 instead of here and see if we still need this change here.

**Comment by tomkerkhove** [comment]
This will be done via #256 & #258
