### ISSUE TITLE
Provide capability to scrape multiple subscriptions

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#761]
Provide capability to scrape multiple subscriptions with one scraper.

**Benefits**:
- Metrics are consolidated into one configuration for multiple subs
- Less scrapers to deploy, operate and manage

**Downside(s)**:
- Scraper requires access to multiple subscriptions for the same Azure AD App. This can be seen as a security concern

Interested in having this? Give it a :+1: and/or comment why you'd like to have this.

**Comment by hajdukd** [comment]
The same functionality used for resourceGroupName override could be reused for subscription, no ?

**Comment by tomkerkhove** [comment]
It could, but for me it's a security boundary but it will most probably come in next couple of months so that you have the flexibility to determine this for you.

**Comment by tomkerkhove** [comment]
We'll make it so!

**Comment by ahurtaud** [comment]
Hello, I am looking at promitor and its resource-discovery. I am wondering if you would consider having auto discovery of all the subscriptions in one tenant ?

AFAIK, at the moment, in the `resource-discovery-declaration.yaml`, **the list of subscriptions has to be set**. Which makes it quite difficult in an environment where subscriptions can be created/removed quite often.

I would like this subscriptions list to be automatically discovered by the resource-discovery so that I can have automatic monitoring of 1 resource type across my tenantID.

Should I create a new feature request?
